/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SendMoneyRouteImport } from './routes/send-money'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectBankRouteImport } from './routes/connect-bank'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SendMoneyRoute = SendMoneyRouteImport.update({
  id: '/send-money',
  path: '/send-money',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectBankRoute = ConnectBankRouteImport.update({
  id: '/connect-bank',
  path: '/connect-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/send-money': typeof SendMoneyRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/send-money': typeof SendMoneyRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/send-money': typeof SendMoneyRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/connect-bank' | '/dashboard' | '/send-money' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect-bank' | '/dashboard' | '/send-money' | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/connect-bank'
    | '/dashboard'
    | '/send-money'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectBankRoute: typeof ConnectBankRoute
  DashboardRoute: typeof DashboardRoute
  SendMoneyRoute: typeof SendMoneyRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-money': {
      id: '/send-money'
      path: '/send-money'
      fullPath: '/send-money'
      preLoaderRoute: typeof SendMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-bank': {
      id: '/connect-bank'
      path: '/connect-bank'
      fullPath: '/connect-bank'
      preLoaderRoute: typeof ConnectBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectBankRoute: ConnectBankRoute,
  DashboardRoute: DashboardRoute,
  SendMoneyRoute: SendMoneyRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
